#!/usr/bin/env bash
# Infinite loop that handles SIGTERM by printing "I am invincible!!!" instead of exiting

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

