#!/usr/bin/env bash
# Forcefully kills the 7-highlander process using SIGKILL (signal 9)

pids=$(pgrep -f 7-highlander)

if [ -z "$pids" ]; then
  exit 0
fi

for pid in $pids; do
  kill -9 "$pid"
done

